### PR TITLE
Fix debian packaging

### PR DESCRIPTION
**Pull request by mdeguzis**
Built on:

```
desktop@steamos:~/SteamOS-Tools-Packaging$ lsb_release -a
No LSB modules are available.
Distributor ID: SteamOS
Description:    SteamOS 2.0
Release:    2.0
Codename:   brewmaster
```
- control file is wrong
- no rules file
- no compat file
- no source/format file
- No change log (example included), needs revision

Built with SteamOS-Tools-Packaging script linked [here](https://github.com/ProfessorKaos64/SteamOS-Tools-Packaging/blob/brewmaster/hid-retrobit/build-hid-retrobit.sh)

Produces:
hid-retrobit_1.0.0+git+SteamOS2-1_all.deb
hid-retrobit_1.0.0+git+SteamOS2-1.debian.tar.xz

Unfortunately, I do not have one of these adapters to test with (only Mayflash adapters). I had to override the dh_auto_install, as your makefile does the installation, followed by your postinst.

Let me know you think.  
Link to full build log: http://slexy.org/view/s2F5rugXVz

### CODE REVIEW

**Comment by mdeguzis** [comment]
Closing for now. Talked to directhex (SteamOS community dev.) 

> Doing the dkms setup in postinst is wrong, as it won't be re-triggered on e.g. kernel upgrade. Basically add a build-dep on dkms, and add a "--with dkms" to the dh call in debian/rules. which means the dh_dkms command will be invoked during package build, which is what the foo.dkms file in debian/ is input for

Once I restructure and test again, i'll resubmit.

**Comment by msteinbeck** [comment]
Ok. Nonetheless, thank you for contributing.

**Comment by mdeguzis** [comment]
Ok, I see now. Your build script uses `dpkg-deb --build DIR` vs what I typically run, `dpkg-buildpackage -rfakeroot -us -uc`. I am not sure how valid [this reasoning](https://raphaelhertzog.com/2010/12/17/do-not-build-a-debian-package-with-dpkg-b/) is. Then the root source files from the root dir into the build dir, sans a standard rules file, which dpkg-deb does not need apparently. I can only guess that if I modeled it after a [typical dkms package](http://anonscm.debian.org/cgit/collab-maint/dm-writeboost.git/tree/debian) from Debian, this will go against your methods of keeping 1 copy in the source tree of some files, so the bare minimum is in DEBIAN and RPM. Do you know if your dpkg-deb build method will in fact rebuild the module after a kernel upgrade?

Sorry if I am not understanding your methods. I don't typically try to package dkms projects.

**Comment by msteinbeck** [comment]
Sorry for my late post, having some deadlines this weak. I'll have a look at your - now closed - pull request next week.

**Pull request closed without merging**
